/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.GUI;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Nguyen Van Hoang
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    ArrayList<JPanel> menuItems = new ArrayList<>();
    ArrayList<JPanel> menuItemLines = new ArrayList<>();
    ArrayList<JLabel> menuItemLabels = new ArrayList<>();
    AboutPanel cardAbout = new AboutPanel();
    AccountPanel cardAccount = new AccountPanel();
    CardLayout cardLayout;
    private final String ABOUT = "about";
    private final String ACCOUNT = "account";
    private final String HOME = "home";
    private final String SING = "SING";
    private final String SONG = "SONG";
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        menuItems.add(plAbout);
        menuItems.add(plHome);
        menuItems.add(plSinger);
        menuItems.add(plSong);
        menuItems.add(plAccount);
        menuItemLines.add(lineAbout);
        menuItemLines.add(lineHome);
        menuItemLines.add(lineSinger);
        menuItemLines.add(lineSong);
        menuItemLines.add(lineAccount);
        menuItemLabels.add(lbAbout);
        menuItemLabels.add(lbAccount);
        menuItemLabels.add(lbHome);
        menuItemLabels.add(lbSinger);
        menuItemLabels.add(lbSong);

        cardLayout = (CardLayout) plCards.getLayout();
        plCards.add(cardAbout, ABOUT);
        plCards.add(cardAccount, ACCOUNT);

        for (JPanel panel : menuItems) {
            panel.setBackground(new Color(0, 0, 0, 0));

        }

        for (JPanel panel : menuItemLines) {
            panel.setBackground(Color.white);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        slidePanel = new javax.swing.JPanel();
        plHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbHome = new javax.swing.JLabel();
        lineHome = new javax.swing.JPanel();
        plSong = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbSong = new javax.swing.JLabel();
        lineSong = new javax.swing.JPanel();
        plSinger = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbSinger = new javax.swing.JLabel();
        lineSinger = new javax.swing.JPanel();
        plAccount = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbAccount = new javax.swing.JLabel();
        lineAccount = new javax.swing.JPanel();
        plAbout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbAbout = new javax.swing.JLabel();
        lineAbout = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        plCards = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setPreferredSize(new java.awt.Dimension(940, 550));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slidePanel.setBackground(new java.awt.Color(68, 142, 246));
        slidePanel.setAutoscrolls(true);
        slidePanel.setLayout(null);

        plHome.setBackground(new java.awt.Color(85, 85, 188));
        plHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plHome.setName("home"); // NOI18N
        plHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeLineColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetColorLine(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chooseMenuItem(evt);
            }
        });
        plHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_home_15px_1.png"))); // NOI18N
        plHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        lbHome.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lbHome.setForeground(new java.awt.Color(255, 255, 255));
        lbHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbHome.setText("Home");
        lbHome.setName("home"); // NOI18N
        plHome.add(lbHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 160, 50));

        lineHome.setBackground(new java.awt.Color(247, 78, 105));
        lineHome.setName("home"); // NOI18N
        lineHome.setPreferredSize(new java.awt.Dimension(1, 20));

        javax.swing.GroupLayout lineHomeLayout = new javax.swing.GroupLayout(lineHome);
        lineHome.setLayout(lineHomeLayout);
        lineHomeLayout.setHorizontalGroup(
            lineHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lineHomeLayout.setVerticalGroup(
            lineHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        plHome.add(lineHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 4, 20));

        slidePanel.add(plHome);
        plHome.setBounds(0, 120, 210, 50);

        plSong.setBackground(new java.awt.Color(85, 85, 188));
        plSong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plSong.setName("song"); // NOI18N
        plSong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeLineColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetColorLine(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chooseMenuItem(evt);
            }
        });
        plSong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_music_notation_15px.png"))); // NOI18N
        plSong.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        lbSong.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lbSong.setForeground(new java.awt.Color(255, 255, 255));
        lbSong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSong.setText("Search Song");
        lbSong.setName("song"); // NOI18N
        plSong.add(lbSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 160, 50));

        lineSong.setBackground(new java.awt.Color(247, 78, 105));
        lineSong.setName("song"); // NOI18N
        lineSong.setPreferredSize(new java.awt.Dimension(4, 20));

        javax.swing.GroupLayout lineSongLayout = new javax.swing.GroupLayout(lineSong);
        lineSong.setLayout(lineSongLayout);
        lineSongLayout.setHorizontalGroup(
            lineSongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        lineSongLayout.setVerticalGroup(
            lineSongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        plSong.add(lineSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        slidePanel.add(plSong);
        plSong.setBounds(0, 170, 210, 50);

        plSinger.setBackground(new java.awt.Color(85, 85, 188));
        plSinger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plSinger.setName("singer"); // NOI18N
        plSinger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeLineColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetColorLine(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chooseMenuItem(evt);
            }
        });
        plSinger.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_rap_15px.png"))); // NOI18N
        plSinger.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        lbSinger.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lbSinger.setForeground(new java.awt.Color(255, 255, 255));
        lbSinger.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSinger.setText("Search Singer");
        lbSinger.setName("singer"); // NOI18N
        plSinger.add(lbSinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 160, 50));

        lineSinger.setBackground(new java.awt.Color(247, 78, 105));
        lineSinger.setName("singer"); // NOI18N
        lineSinger.setPreferredSize(new java.awt.Dimension(4, 20));

        javax.swing.GroupLayout lineSingerLayout = new javax.swing.GroupLayout(lineSinger);
        lineSinger.setLayout(lineSingerLayout);
        lineSingerLayout.setHorizontalGroup(
            lineSingerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        lineSingerLayout.setVerticalGroup(
            lineSingerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        plSinger.add(lineSinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        slidePanel.add(plSinger);
        plSinger.setBounds(0, 220, 210, 50);

        plAccount.setBackground(new java.awt.Color(85, 85, 188));
        plAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plAccount.setName("account"); // NOI18N
        plAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeLineColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetColorLine(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chooseMenuItem(evt);
            }
        });
        plAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_user_15px.png"))); // NOI18N
        plAccount.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        lbAccount.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lbAccount.setForeground(new java.awt.Color(255, 255, 255));
        lbAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbAccount.setText("Account");
        plAccount.add(lbAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1, 160, 50));

        lineAccount.setBackground(new java.awt.Color(247, 78, 105));
        lineAccount.setName("account"); // NOI18N
        lineAccount.setPreferredSize(new java.awt.Dimension(4, 20));

        javax.swing.GroupLayout lineAccountLayout = new javax.swing.GroupLayout(lineAccount);
        lineAccount.setLayout(lineAccountLayout);
        lineAccountLayout.setHorizontalGroup(
            lineAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        lineAccountLayout.setVerticalGroup(
            lineAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        plAccount.add(lineAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        slidePanel.add(plAccount);
        plAccount.setBounds(0, 270, 210, 50);

        plAbout.setBackground(new java.awt.Color(85, 85, 188));
        plAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plAbout.setName("about"); // NOI18N
        plAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeLineColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetColorLine(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chooseMenuItem(evt);
            }
        });
        plAbout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_info_15px.png"))); // NOI18N
        plAbout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        lbAbout.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lbAbout.setForeground(new java.awt.Color(255, 255, 255));
        lbAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbAbout.setText("About Us");
        plAbout.add(lbAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1, 160, 50));

        lineAbout.setBackground(new java.awt.Color(247, 78, 105));
        lineAbout.setName("about"); // NOI18N
        lineAbout.setPreferredSize(new java.awt.Dimension(4, 20));

        javax.swing.GroupLayout lineAboutLayout = new javax.swing.GroupLayout(lineAbout);
        lineAbout.setLayout(lineAboutLayout);
        lineAboutLayout.setHorizontalGroup(
            lineAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        lineAboutLayout.setVerticalGroup(
            lineAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        plAbout.add(lineAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        slidePanel.add(plAbout);
        plAbout.setBounds(0, 320, 210, 50);
        slidePanel.add(jSeparator1);
        jSeparator1.setBounds(20, 80, 160, 10);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Sing");
        slidePanel.add(jLabel12);
        jLabel12.setBounds(40, 40, 50, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cheers-204742_1280.jpg"))); // NOI18N
        slidePanel.add(jLabel13);
        jLabel13.setBounds(-160, 0, 370, 600);

        bgPanel.add(slidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 600));

        plCards.setBackground(new java.awt.Color(68, 142, 246));
        plCards.setLayout(new java.awt.CardLayout());
        bgPanel.add(plCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 730, 570));

        btnClose.setBackground(new java.awt.Color(255, 51, 51));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCloseMousePressed(evt);
            }
        });
        bgPanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseMousePressed

    private void changeLineColor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeLineColor
        // TODO add your handling code here:
        String nameComp = evt.getComponent().getName();
        for (JPanel panel : menuItemLines) {
            if (panel.getName().equals(nameComp)) {
                panel.setBackground(new Color(247, 78, 105));
                break;
            }
        }


    }//GEN-LAST:event_changeLineColor

    private void resetColorLine(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetColorLine
        // TODO add your handling code here:
        String nameComp = evt.getComponent().getName();
        for (JPanel panel : menuItemLines) {
            if (panel.getName().equals(nameComp)) {
                panel.setBackground(Color.white);
                break;
            }
        }


    }//GEN-LAST:event_resetColorLine

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        btnClose.setForeground(Color.WHITE);
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.RED);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        btnClose.setForeground(Color.black);
        btnClose.setBackground(Color.white);
    }//GEN-LAST:event_btnCloseMouseExited

    private void chooseMenuItem(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseMenuItem
        // TODO add your handling code here:
        String nameComp = evt.getComponent().getName();
        switchCard(nameComp);
    }//GEN-LAST:event_chooseMenuItem
    private void switchCard(String cardName) {
        // TODO add your handling code here:

        switch (cardName) {
            case ABOUT: {
                cardLayout.show(plCards, ABOUT);
                System.out.println("About");
                break;
            }
            case ACCOUNT: {
                cardLayout.show(plCards, ACCOUNT);
                System.out.println("Account");
                break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAbout;
    private javax.swing.JLabel lbAccount;
    private javax.swing.JLabel lbHome;
    private javax.swing.JLabel lbSinger;
    private javax.swing.JLabel lbSong;
    private javax.swing.JPanel lineAbout;
    private javax.swing.JPanel lineAccount;
    private javax.swing.JPanel lineHome;
    private javax.swing.JPanel lineSinger;
    private javax.swing.JPanel lineSong;
    private javax.swing.JPanel plAbout;
    private javax.swing.JPanel plAccount;
    private javax.swing.JPanel plCards;
    private javax.swing.JPanel plHome;
    private javax.swing.JPanel plSinger;
    private javax.swing.JPanel plSong;
    private javax.swing.JPanel slidePanel;
    // End of variables declaration//GEN-END:variables
}
